// boilerplate/reactjs/src/pages/RegisterPage.tsx
import React, { useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from 'features/auth/useAuth';

export const RegisterPage: React.FC = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const { register, isLoading } = useAuth();

  const handleSubmit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();
      setError('');
      if (password !== confirmPassword) { setError('Passwords do not match.'); return; }
      if (password.length < 8) { setError('Password must be at least 8 characters.'); return; }
      try { await register(email, password); }
      catch { setError('Registration failed. Email may already be in use.'); }
    },
    [email, password, confirmPassword, register],
  );

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="w-full max-w-md card p-8">
        <h1 className="text-2xl font-bold text-gray-900 mb-1">Create account</h1>
        <p className="text-sm text-gray-500 mb-6">Get started managing your orders</p>

        {error && (
          <div className="mb-4 p-3 rounded-lg bg-red-50 text-red-700 text-sm">{error}</div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label htmlFor="reg-email" className="block text-sm font-medium text-gray-700 mb-1">Email</label>
            <input
              id="reg-email" type="email" required autoComplete="email"
              className="input" value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
            />
          </div>

          <div>
            <label htmlFor="reg-password" className="block text-sm font-medium text-gray-700 mb-1">Password</label>
            <input
              id="reg-password" type="password" required autoComplete="new-password"
              className="input" value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Min. 8 characters"
            />
          </div>

          <div>
            <label htmlFor="reg-confirm" className="block text-sm font-medium text-gray-700 mb-1">Confirm</label>
            <input
              id="reg-confirm" type="password" required autoComplete="new-password"
              className="input" value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              placeholder="Re-enter"
            />
          </div>

          <button type="submit" disabled={isLoading} className="btn-primary w-full">
            {isLoading ? 'Creating…' : 'Create account'}
          </button>
        </form>

        <p className="mt-6 text-center text-sm text-gray-600">
          Already have an account?{' '}
          <Link to="/login" className="text-brand-600 hover:underline font-medium">Sign in</Link>
        </p>
      </div>
    </div>
  );
};

export default RegisterPage;

// boilerplate/quasar/src/pages/RegisterPage.vue
<template>
  <div class="flex flex-center column" style="min-height: 100vh;">
    <q-card class="q-pa-md" style="width: 400px; max-width: 90vw;">
      <q-card-section>
        <div class="text-h6 text-center">Create Account</div>
        <div class="text-caption text-grey text-center q-mt-sm">
          Join our community today.
        </div>
      </q-card-section>

      <q-card-section>
        <q-form @submit.prevent="handleSubmit">
          <q-input
            v-model="username"
            label="Username"
            outlined
            dense
            :error="!!usernameError"
            :error-message="usernameError"
            data-testid="register-username-input"
            @update:model-value="clearFieldError('username')"
          />

          <q-input
            v-model="email"
            label="Email"
            type="email"
            outlined
            dense
            class="q-mt-sm"
            :error="!!emailError"
            :error-message="emailError"
            data-testid="register-email-input"
            @update:model-value="clearFieldError('email')"
          />

          <q-input
            v-model="password"
            label="Password"
            type="password"
            outlined
            dense
            class="q-mt-sm"
            :error="!!passwordError"
            :error-message="passwordError"
            data-testid="register-password-input"
            @update:model-value="clearFieldError('password')"
          />

          <div v-if="generalError" class="text-negative text-center q-mt-sm" data-testid="register-general-error">
            {{ generalError }}
          </div>

          <q-btn
            type="submit"
            color="primary"
            label="Register"
            class="full-width q-mt-md"
            data-testid="register-submit-button"
          />

          <div class="text-center q-mt-md">
            Already have an account?
            <q-btn flat no-caps label="Login" @click="router.push('/')" data-testid="register-login-link" />
          </div>
        </q-form>
      </q-card-section>
    </q-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const router = useRouter()
const auth = useAuthStore()

const username = ref('')
const email = ref('')
const password = ref('')
const usernameError = ref('')
const emailError = ref('')
const passwordError = ref('')
const generalError = ref('')

function clearFieldError(field: string) {
  if (field === 'username') usernameError.value = ''
  if (field === 'email') emailError.value = ''
  if (field === 'password') passwordError.value = ''
}

async function handleSubmit() {
  usernameError.value = ''
  emailError.value = ''
  passwordError.value = ''
  generalError.value = ''

  let hasError = false
  if (!username.value) {
    usernameError.value = 'Username is required'
    hasError = true
  }
  if (!email.value || !email.value.includes('@')) {
    emailError.value = 'Valid email is required'
    hasError = true
  }
  if (password.value.length < 6) {
    passwordError.value = 'Password must be at least 6 characters'
    hasError = true
  }

  if (hasError) return

  const success = await auth.register(username.value, email.value, password.value)
  if (success) {
    router.push('/')
  } else {
    generalError.value = auth.error || 'Registration failed'
  }
}
</script>
